/**
 * Slugs the engine owns. `index.md` (the catalog) and `log.md` (the append-only
 * record) are generated by the engine and will be overwritten
 */
export const RESERVED_SLUGS = new Set(["index", "log"]);

/**
 * File formats Obsidian renders inline for an `![[..]]` embed — what separates an
 * asset reference from a note transclusion when parsing wikilinks.
 */
export const EMBEDDABLE_FILE =
  /\.(png|jpe?g|gif|bmp|svg|webp|avif|mp3|wav|m4a|ogg|3gp|flac|mp4|webm|ogv|mov|mkv|pdf)$/i;
