import matter from "gray-matter";
import { DEFAULT_PAGE_ROLE, RESERVED_SLUGS, ROLES, slugify, roleRank, type Page } from "@sammer/shared";
import type { Indexer } from "../index/indexer.js";
import type { WikiStore } from "./store.js";
import { extractLinks } from "./links.js";
import { parsePage } from "./format.js";

export interface SavePageInput {
  title: string;
  body: string;
  summary: string;
  category?: string;
  tags?: string[];
  slug?: string;
}

export class WikiService {
  constructor(
    private readonly store: WikiStore,
    private readonly indexer: Indexer,
  ) {}

  async savePage(input: SavePageInput): Promise<Page> {
    const slug = slugify(input.slug ?? input.title);
    // index.md and log.md are generated by the engine and only filtered out on
    // the way back, so nothing else stops a page titled "Index" from landing on
    // the catalog and erasing it. Throwing reaches the model as a tool error it
    // can recover from by picking another title.
    if (RESERVED_SLUGS.has(slug)) {
      throw new Error(`"${slug}" is a reserved slug maintained by sammer; choose another title.`);
    }
    const existing = await this.store.read(slug);
    const now = new Date().toISOString();

    const page: Page = {
      metadata: {
        id: existing?.metadata.id ?? slug,
        title: input.title,
        slug,
        category: input.category ?? existing?.metadata.category ?? "Uncategorized",
        tags: input.tags ?? existing?.metadata.tags ?? [],
        summary: input.summary || existing?.metadata.summary || "",
        created: existing?.metadata.created ?? now,
        updated: now,
        sources: existing?.metadata.sources ?? [],
        role: existing?.metadata.role ?? DEFAULT_PAGE_ROLE,
      },
      body: input.body,
      links: extractLinks(input.body),
    };

    // Disk first: the markdown is the source of truth, and the index is only
    // worth updating for something that actually persisted.
    await this.store.write(page);
    this.indexer.upsertPage(page);
    return page;
  }

  // bypasses and stores string in pages directly
  async saveRaw(slug: string, raw: string): Promise<Page> {
    if (slug !== slugify(slug)) {
      throw new Error(`"${slug}" is not a valid slug.`);
    }
    if (RESERVED_SLUGS.has(slug)) {
      throw new Error(`"${slug}" is a reserved, engine-generated file and cannot be edited directly.`);
    }
    const { data } = matter(raw);
    if (typeof data.title !== "string" || !data.title.trim()) {
      throw new Error(`frontmatter is invalid: "title" is required.`);
    }
    if (data.role !== undefined && !(ROLES as readonly string[]).includes(data.role)) {
      throw new Error(`frontmatter is invalid: "role" must be one of ${ROLES.join(", ")}.`);
    }

    const existing = await this.store.read(slug);
    const now = new Date().toISOString();
    const page = parsePage(slug, raw, { created: existing?.metadata.created ?? now, updated: now });

    await this.store.writeText(slug, raw);
    this.indexer.upsertPage(page);
    return page;
  }

  // The engine-maintained files (index.md, log.md) are generated markdown, not
  // pages with frontmatter — read as raw text rather than through getPage.
  async readText(slug: string): Promise<string | null> {
    return this.store.readText(slug);
  }

  async getPage(slug: string, maxRank: number = roleRank("admin")): Promise<Page | null> {
    const page = await this.store.read(slug);
    if (!page) return null;
    if (roleRank(page.metadata.role ?? DEFAULT_PAGE_ROLE) > maxRank) return null;
    return page;
  }

  async listPages(): Promise<string[]> {
    return this.store.list();
  }

  // The index is derived, so it is rebuilt from the markdown rather than trusted.
  async reindex(): Promise<void> {
    for (const slug of await this.store.list()) {
      const page = await this.store.read(slug);
      if (page) this.indexer.upsertPage(page);
    }
  }
}
