import { RESERVED_SLUGS, slugify, type Page } from "@sammer/shared";
import type { Indexer } from "../index/indexer.js";
import type { WikiStore } from "./store.js";
import { extractLinks } from "./links.js";

export interface SavePageInput {
  title: string;
  body: string;
  summary: string;
  category?: string;
  tags?: string[];
  slug?: string;
}

export class WikiService {
  constructor(
    private readonly store: WikiStore,
    private readonly indexer: Indexer,
  ) {}

  async savePage(input: SavePageInput): Promise<Page> {
    const slug = slugify(input.slug ?? input.title);
    // index.md and log.md are generated by the engine and only filtered out on
    // the way back, so nothing else stops a page titled "Index" from landing on
    // the catalog and erasing it. Throwing reaches the model as a tool error it
    // can recover from by picking another title.
    if (RESERVED_SLUGS.has(slug)) {
      throw new Error(`"${slug}" is a reserved slug maintained by sammer; choose another title.`);
    }
    const existing = await this.store.read(slug);
    const now = new Date().toISOString();

    const page: Page = {
      metadata: {
        id: existing?.metadata.id ?? slug,
        title: input.title,
        slug,
        category: input.category ?? existing?.metadata.category ?? "Uncategorized",
        tags: input.tags ?? existing?.metadata.tags ?? [],
        summary: input.summary || existing?.metadata.summary || "",
        created: existing?.metadata.created ?? now,
        updated: now,
        sources: existing?.metadata.sources ?? [],
      },
      body: input.body,
      links: extractLinks(input.body),
    };

    // Disk first: the markdown is the source of truth, and the index is only
    // worth updating for something that actually persisted.
    await this.store.write(page);
    this.indexer.upsertPage(page);
    return page;
  }

  async getPage(slug: string): Promise<Page | null> {
    return this.store.read(slug);
  }

  async listPages(): Promise<string[]> {
    return this.store.list();
  }

  // The index is derived, so it is rebuilt from the markdown rather than trusted.
  async reindex(): Promise<void> {
    for (const slug of await this.store.list()) {
      const page = await this.store.read(slug);
      if (page) this.indexer.upsertPage(page);
    }
  }
}
